# Generated by Django 4.2.5 on 2023-10-05 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_populateduserserializer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PopulatedUserSerializer',
        ),
    ]
