# Generated by Django 4.2.5 on 2023-10-16 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_user_friends_remove_user_messages_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='collection',
        ),
    ]
