# Generated by Django 4.2.5 on 2023-10-06 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_likes'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='games',
            field=models.ManyToManyField(blank=True, related_name='category_games', to='games.game'),
        ),
    ]
