# Generated by Django 4.2.5 on 2023-10-06 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_likes'),
        ('categories', '0002_category_games'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='games',
            field=models.ManyToManyField(blank=True, related_name='category_game', to='games.game'),
        ),
    ]
