# Generated by Django 4.2.5 on 2023-10-16 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_alter_category_games'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='games',
        ),
    ]
