# Generated by Django 4.2.5 on 2023-10-06 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_likes'),
        ('mechanics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanic',
            name='games',
            field=models.ManyToManyField(blank=True, related_name='mechanic_game', to='games.game'),
        ),
    ]
