# Generated by Django 4.2.5 on 2023-10-16 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mechanics', '0002_mechanic_games'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mechanic',
            name='games',
        ),
    ]
