# Generated by Django 4.2.5 on 2023-10-03 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('mechanics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('thumbnail', models.URLField()),
                ('image', models.URLField()),
                ('name', models.CharField()),
                ('description', models.CharField()),
                ('yearpublished', models.PositiveIntegerField()),
                ('minplayers', models.PositiveIntegerField()),
                ('maxplayers', models.PositiveIntegerField()),
                ('playingtime', models.PositiveIntegerField()),
                ('minage', models.PositiveIntegerField()),
                ('categories', models.ManyToManyField(blank=True, related_name='game_category', to='categories.category')),
                ('mechanics', models.ManyToManyField(blank=True, related_name='game_mechanic', to='mechanics.mechanic')),
            ],
        ),
    ]
