# Generated by Django 4.2.5 on 2023-10-13 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='image',
        ),
    ]
