# Generated by Django 4.2.5 on 2023-10-16 08:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0004_game_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='likes',
        ),
        migrations.AddField(
            model_name='game',
            name='owned',
            field=models.ManyToManyField(blank=True, related_name='owned_games', to=settings.AUTH_USER_MODEL),
        ),
    ]
